#!/bin/zsh
# Author : Shivam Garg

workspace='' # Add the bitbucket workspace name here
target='develop'
current=$(git branch --show-current)
repo=$(basename `git rev-parse --show-toplevel`)

if [[ "$1" == "-h" ]]; then
  echo "Script for creating Bitbucket PR from terminal
  where:
       -h show this help text
       -t target branch (default - 'develop')
       -c branch of which you want to create the PR for (default - current branch)
       -r repository (default - current repo)
  usage example:
        create_pr -> For creating the PR from current branch to develop
        create_pr -t release_branch -> For creating the PR from current branch to release_branch"
  exit 0
fi

while getopts "c:t:r:" opt
do
   case "$opt" in
      c ) current="$OPTARG" ;;
      t ) target="$OPTARG" ;;
      r ) repo="$OPTARG" ;;
      ? )  ;;
   esac
done

if [ -z "$repo" ]
then
   echo "Enter the current branch with option -r";
   exit 1;
fi

if [ -z "$current" ]
then
   echo "Enter the current branch with option -c";
   exit 1;
fi

# Adding title as current branch after removing '_' and '-'
title=${current//'_'/' '}
title=${title//'-'/' '}
title=${(C)title}

# Adding description as list of all commit message
description=$(git log --reverse --pretty=format:"* %s" $target..$current)
description=${description//
/'\n'}

echo 'https://bitbucket.org/api/2.0/repositories/'"$workspace"'/'"$repo"'/pullrequests'
echo "$current" "$target" "$title"
echo "$description"

# Create App passwords from Bitbucket Personal settings page
curl --location --request POST -u USERNAME:PASSWORD 'https://bitbucket.org/api/2.0/repositories/'"$workspace"'/'"$repo"'/pullrequests' --header 'Content-Type: application/json' --data-raw '{
    "title": "'"$title"'",
    "description": "'"$description"'",
    "source": {
        "branch": {
            "name": "'"$current"'"
        }
    },
    "destination": {
        "branch": {
            "name": "'"$target"'"
        }
    },
    "reviewers": [],
    "close_source_branch": true
}' | jq '.links.html,.error'
